spring:
  application:
    name: produtosapi
  datasource:
    url: jdbc:h2:mem:produtos
    username: mt
    password: paw
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    